Repository microsoft/AzureTRE, pull requests merged in 2021-05, with the labels that each got.

#45 Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/research_spike.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/pull_request_template.md
Labels: enhancement

#47 Deploy API to App service plan and automate deployment
  .github/workflows/deploy_api.yml
  core/README.md
  core/api/main.py
  core/api_tests/__init__.py
Labels: api

#99 Fix paths in make_images.sh and documentation after API code restructure
  .yaspellerrc.json
  devops/scripts/build_images.sh
  docs/developer-quickstart.md
  templates/core/terraform/appgateway/appgateway.tf
Labels: bug

#106 Configure the appgw backend setting for api to use custom probe
  templates/core/terraform/appgateway/appgateway.tf
  templates/core/terraform/appgateway/locals.tf
Labels: templates

#116 The first iteration of the vanilla workspace bundle
  .dockerignore
  .gitignore
  templates/workspaces/base_workspace/terraform/.env.sample
  templates/workspaces/base_workspace/terraform/.terraform.lock.hcl
  templates/workspaces/base_workspace/terraform/deploy.sh
  templates/workspaces/base_workspace/terraform/destroy.sh
  templates/workspaces/base_workspace/terraform/locals.tf
  templates/workspaces/base_workspace/terraform/main.tf
  templates/workspaces/base_workspace/terraform/variables.tf
  workspaces/vanilla/Dockerfile.tmpl
  workspaces/vanilla/README.md
  workspaces/vanilla/porter.yaml
  workspaces/vanilla/terraform/locals.tf
  workspaces/vanilla/terraform/main.tf
  workspaces/vanilla/terraform/network/locals.tf
  workspaces/vanilla/terraform/network/network.tf
  workspaces/vanilla/terraform/network/variables.tf
  workspaces/vanilla/terraform/outputs.tf
  workspaces/vanilla/terraform/variables.tf
Labels: bundles

#121 Adds the vanilla workspace bundle to ACR
  .github/workflows/tre-CD.yml
  Makefile
  devops/scripts/install_porter.sh
  devops/scripts/publish_vanilla_workspace.sh
Labels: bundles, templates

#123 Implement [GET] /workspaces
  management_api_app/api/dependencies/__init__.py
  management_api_app/api/dependencies/database.py
  management_api_app/api/dependencies/workspaces.py
  management_api_app/api/routes/api.py
  management_api_app/api/routes/workspaces.py
  management_api_app/core/config.py
  management_api_app/core/events.py
  management_api_app/db/errors.py
  management_api_app/db/events.py
  management_api_app/db/repositories/base.py
  management_api_app/db/repositories/workspaces.py
  management_api_app/main.py
  management_api_app/models/domain/azuretremodel.py
  management_api_app/models/domain/resource.py
  management_api_app/models/schemas/resource.py
  management_api_app/resources/strings.py
  management_api_app/tests/test_api/conftest.py
  management_api_app/tests/test_api/test_routes/test_workspaces.py
  scripts/__init__.py
  scripts/bootstrap_db_for_local_tests.py
Labels: api

#129 Adds initial workspace authoring documentation
  docs/authoring-workspaces.md
  docs/quickstart.md
Labels: bundles, documentation

#136 Harmonizes the vanilla workspace bundle and docs
  docs/authoring-workspaces.md
  workspaces/vanilla/README.md
  workspaces/vanilla/porter.yaml
  workspaces/vanilla/terraform/locals.tf
  workspaces/vanilla/terraform/main.tf
  workspaces/vanilla/terraform/network/network.tf
  workspaces/vanilla/terraform/network/variables.tf
  workspaces/vanilla/terraform/variables.tf
Labels: bundles, documentation
