Repository microsoft/AzureTRE, pull requests merged in 2022-02, with the labels that each got.

#1196 Use DevContainer for the build
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/e2e.yml
  Makefile
  devops/terraform/bootstrap.sh
  e2e_tests/test_workspace_service_creation.py
  templates/core/terraform/keyvault/variables.tf
  templates/core/terraform/variables.tf
Labels: safe to test

#1222 Removing TF_VAR_tre_id
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/lets_encrypt.yml
  templates/core/terraform/deploy.sh
  templates/core/terraform/destroy.sh
  templates/core/terraform/import.sh
  templates/core/terraform/outputs.sh
  templates/shared_services/gitea/terraform/deploy.sh
  templates/shared_services/gitea/terraform/destroy.sh
  templates/shared_services/sonatype-nexus/terraform/deploy.sh
  templates/shared_services/sonatype-nexus/terraform/destroy.sh
  templates/workspace_services/azureml/terraform/deploy.sh
  templates/workspace_services/guacamole/terraform/deploy.sh
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/deploy.sh
  templates/workspaces/base/terraform/deploy.sh
  templates/workspaces/base/terraform/destroy.sh
Labels: safe to test

#1223 Removing TF_VAR_location
  .github/actions/devcontainer_run_command/action.yml
  devops/terraform/bootstrap.sh
Labels: safe to test

#1253 Add recover to KeyVault access policy to enable TF to recover deleted secrets
  templates/core/terraform/keyvault/keyvault.tf
Labels: safe to test

#1236 Fixing missing Resource Group
  templates/core/terraform/json-to-env.sh
  templates/core/terraform/keyvault/keyvault.tf
  templates/core/terraform/outputs.tf
  templates/core/terraform/scripts/letsencrypt.sh
  templates/core/terraform/scripts/upload_static_web.sh
Labels: safe to test

#1250 Setup debug experience for api development
  .gitignore
  .vscode/launch.json
  Makefile
  devops/scripts/setup_local_api_debugging.sh
  docs/tre-developers/api.md
  templates/core/terraform/json-to-env.sh
  templates/core/terraform/outputs.sh
  templates/core/terraform/outputs.tf
Labels: safe to test

#1235 Add config to save dev container bash history to the mounted volume
  .devcontainer/Dockerfile
Labels: safe to test

#1153 Operations History
  api_app/.env.sample
  api_app/api/dependencies/workspaces.py
  api_app/api/routes/workspaces.py
  api_app/core/config.py
  api_app/db/repositories/operations.py
  api_app/db/repositories/resources.py
  api_app/db/repositories/user_resources.py
  api_app/db/repositories/workspace_services.py
  api_app/db/repositories/workspaces.py
  api_app/models/domain/operation.py
  api_app/models/domain/resource.py
  api_app/models/domain/user_resource.py
  api_app/models/domain/workspace.py
  api_app/models/domain/workspace_service.py
  api_app/models/schemas/operation.py
  api_app/models/schemas/user_resource.py
  api_app/models/schemas/workspace.py
  api_app/models/schemas/workspace_service.py
  api_app/resources/strings.py
  api_app/service_bus/deployment_status_update.py
  api_app/service_bus/resource_request_sender.py
  api_app/services/authentication.py
  api_app/tests_ma/test_api/test_routes/test_api_access.py
  api_app/tests_ma/test_api/test_routes/test_workspaces.py
  api_app/tests_ma/test_db/test_repositories/test_resource_repository.py
  api_app/tests_ma/test_db/test_repositories/test_user_resource_repository.py
  api_app/tests_ma/test_db/test_repositories/test_workpaces_repository.py
  api_app/tests_ma/test_db/test_repositories/test_workpaces_service_repository.py
  api_app/tests_ma/test_models/test_resource.py
  api_app/tests_ma/test_service_bus/test_deployment_status_update.py
  api_app/tests_ma/test_service_bus/test_resource_request_sender.py
  api_app/tests_ma/test_services/test_aad_access_service.py
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  docs/tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md
  e2e_tests/helpers.py
  e2e_tests/test_workspace_creation.py
  e2e_tests/test_workspace_service_creation.py
  resource_processor/vmss_porter/runner.py
  scripts/aad-app-reg.sh
  scripts/db_migrations.py
Labels: safe to test, breaking-change

#1257 Register AAD workspace - developer experience
  .vscode/launch.json
  .vscode/tasks.json
  Makefile
  devops/scripts/register-aad-workspace.sh
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  templates/core/terraform/outputs.sh
Labels: safe to test

#1262 Add automation app support
  Makefile
  devops/scripts/build_and_register_bundle.sh
  devops/scripts/publish_register_bundle.sh
  docs/tre-admins/auth.md
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  docs/tre-admins/setup-instructions/pre-deployment-steps.md
  scripts/aad-app-reg.sh
  templates/core/.env.sample
Labels: safe to test

#1242 Azure testing in PR validation
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/clean_validation_envs.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/e2e.yml
  Makefile
  devops/scripts/clean_ci_validation_envs.sh
  devops/terraform/deploy.sh
  templates/core/terraform/main.tf
  templates/core/terraform/variables.tf
Labels: safe to test

#1270 Fix PR trigger in deployments and E2Es on main
  .github/workflows/deploy_tre.yml
  .github/workflows/e2e.yml
Labels: safe to test

#1273 CICD deployments with a reusable workflow
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_reusable.yml
  devops/scripts/clean_ci_validation_envs.sh
Labels: safe to test

#1272 Devcontainer cache for main and PR
  .devcontainer/Dockerfile
  .devcontainer/scripts/gh.sh
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_reusable.yml
  Makefile
Labels: safe to test

#1234 Consolidated TF modules
  .devcontainer/Dockerfile
  .github/workflows/lets_encrypt.yml
  resource_processor/vmss_porter/Dockerfile
  templates/core/terraform/admin-jumpbox.tf
  templates/core/terraform/admin-jumpbox/variables.tf
  templates/core/terraform/api-webapp.tf
  templates/core/terraform/api-webapp/data.tf
  templates/core/terraform/api-webapp/locals.tf
  templates/core/terraform/api-webapp/output.tf
  templates/core/terraform/api-webapp/variables.tf
  templates/core/terraform/bastion.tf
  templates/core/terraform/identity.tf
  templates/core/terraform/keyvault.tf
  templates/core/terraform/keyvault/output.tf
  templates/core/terraform/keyvault/variables.tf
  templates/core/terraform/main.tf
  templates/core/terraform/modules_move_definitions.tf
  templates/core/terraform/outputs.tf
  templates/core/terraform/routetable.tf
  templates/core/terraform/routetable/variables.tf
  templates/core/terraform/servicebus.tf
  templates/core/terraform/servicebus/output.tf
  templates/core/terraform/servicebus/variables.tf
  templates/core/terraform/state-store/output.tf
  templates/core/terraform/state-store/variables.tf
  templates/core/terraform/statestore.tf
  templates/core/terraform/storage.tf
  templates/core/terraform/storage/output.tf
  templates/core/terraform/storage/variables.tf
  templates/core/terraform/user-assigned-identity/output.tf
  templates/core/terraform/user-assigned-identity/variables.tf
Labels: safe to test

#1279 convert pull_request_target trigger to pull_request
  .github/workflows/build_docker_images.yml
  .github/workflows/build_validation_develop.yml
  .github/workflows/codeql-analysis.yml
Labels: safe to test

#1281 Preserve Resource Property History
  api_app/api/routes/workspaces.py
  api_app/db/repositories/base.py
  api_app/db/repositories/resources.py
  api_app/db/repositories/user_resources.py
  api_app/db/repositories/workspace_services.py
  api_app/db/repositories/workspaces.py
  api_app/models/domain/operation.py
  api_app/models/domain/resource.py
  api_app/models/schemas/resource.py
  api_app/models/schemas/user_resource.py
  api_app/models/schemas/workspace.py
  api_app/models/schemas/workspace_service.py
  api_app/models/schemas/workspace_template.py
  api_app/resources/strings.py
  api_app/schemas/workspace.json
  api_app/service_bus/deployment_status_update.py
  api_app/tests_ma/test_api/test_routes/test_api_access.py
  api_app/tests_ma/test_api/test_routes/test_workspaces.py
  api_app/tests_ma/test_db/test_repositories/test_resource_repository.py
  api_app/tests_ma/test_db/test_repositories/test_user_resource_repository.py
  api_app/tests_ma/test_db/test_repositories/test_workpaces_repository.py
  api_app/tests_ma/test_db/test_repositories/test_workpaces_service_repository.py
  api_app/tests_ma/test_models/test_resource.py
  api_app/tests_ma/test_service_bus/test_deployment_status_update.py
  api_app/tests_ma/test_service_bus/test_resource_request_sender.py
  api_app/tests_ma/test_services/test_aad_access_service.py
  e2e_tests/helpers.py
Labels: safe to test

#1283 Validate the custom address space
  .gitignore
  .vscode/settings.json
  api_app/db/errors.py
  api_app/db/repositories/workspaces.py
  api_app/services/cidr_service.py
  api_app/tests_ma/test_db/test_repositories/test_workpaces_repository.py
  api_app/tests_ma/test_services/test_cidr_service.py
Labels: safe to test

#1286 Add unit tests into build validation
  .github/workflows/build_docker_images.yml
  .github/workflows/build_validation_develop.yml
  .gitignore
Labels: safe to test

#1264 Removed devcontainer workspace folder
  .devcontainer/devcontainer.json
Labels: safe to test

#1280 Use Docker BuildKit cache in builds when running via make
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/deploy_tre_reusable.yml
  Makefile
Labels: safe to test

#1282 Enable ci environment cleanup
  .github/workflows/clean_validation_envs.yml
  devops/scripts/clean_ci_validation_envs.sh
Labels: safe to test

#1292 Fix dns zone terraform dependencies
  templates/core/terraform/admin-jumpbox.tf
  templates/core/terraform/bastion/variables.tf
  templates/core/terraform/keyvault.tf
  templates/core/terraform/main.tf
  templates/core/terraform/resource_processor/vmss_porter/main.tf
  templates/core/terraform/resource_processor/vmss_porter/variables.tf
  templates/core/terraform/statestore.tf
  templates/core/terraform/storage.tf
  templates/core/terraform/variables.tf
Labels: safe to test

#1295 Fix - Delete redundant trace line
  resource_processor/vmss_porter/runner.py
Labels: safe to test

#1296 Enable e2e smoke tests to use automation account
  .devcontainer/devcontainer.json
  .vscode/settings.json
  e2e_tests/config.py
  e2e_tests/conftest.py
  e2e_tests/pytest.ini
Labels: safe to test

#1289 Jjgriff93/1276 fix admin set-up docs
  docs/tre-admins/setup-instructions/deploying-azure-tre.md
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  docs/tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md
  docs/tre-admins/setup-instructions/pre-deployment-steps.md
  docs/tre-templates/user-resources/guacamole-linux-vm.md
  docs/tre-templates/user-resources/guacamole-windows-vm.md
  docs/tre-templates/workspace-services/azure-ml.md
  docs/tre-templates/workspace-services/dev-test-labs.md
  docs/tre-templates/workspace-services/guacamole.md
  docs/tre-templates/workspaces/base.md
  docs/tre-templates/workspaces/inner-eye.md
  scripts/aad-app-reg.sh
Labels: safe to test

#1263 Add project status note
  README.md
Labels: safe to test

#1302 Simpler bundle registration
  .github/workflows/deploy_tre_reusable.yml
  Makefile
  devops/scripts/build_and_register_bundle.sh
  devops/scripts/publish_register_bundle.sh
  devops/scripts/register_bundle_with_api.sh
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  docs/tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md
  docs/tre-templates/user-resources/guacamole-linux-vm.md
  docs/tre-templates/user-resources/guacamole-windows-vm.md
  docs/tre-templates/workspace-services/azure-ml.md
  docs/tre-templates/workspace-services/dev-test-labs.md
  docs/tre-templates/workspace-services/guacamole.md
  docs/tre-templates/workspaces/base.md
  docs/tre-templates/workspaces/inner-eye.md
Labels: safe to test

#1304 Unit Tests only run if api_app has changed and are executed from docker build
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/build_docker_images.yml
  .github/workflows/build_validation_develop.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_reusable.yml
  .gitignore
  .vscode/tasks.json
  api_app/Dockerfile
  api_app/run_tests_and_exit_succesfully.sh
  templates/workspace_services/guacamole/guacamole-server/docker/Dockerfile
  templates/workspace_services/guacamole/guacamole-server/docker/maven_package_and_exit_succesfully.sh
Labels: safe to test

#1294 E2E - fix guacamole test
  e2e_tests/test_workspace_service_creation.py
  templates/workspace_services/guacamole/porter.yaml
Labels: safe to test

#1310 Configure WindowsVMs to use PyPI proxy
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/porter.yaml
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/locals.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/pypi_sources_config.ps1
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/windowsvm.tf
Labels: safe to test

#1311 #1301-Fix-LinuxVMScaleSetPasswordRequirements
  templates/core/terraform/resource_processor/vmss_porter/main.tf
Labels: safe to test

#1315 fix urls
  docs/tre-templates/workspaces/inner-eye.md
Labels: safe to test

#1312 #1309-Fix-DocumentationCorrectionsAndFormatting
  docs/tre-admins/setup-instructions/deploying-azure-tre.md
  docs/tre-admins/setup-instructions/installing-base-workspace.md
  docs/tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md
Labels: documentation

#1329 Make tre-destroy run (again)
  Makefile
  templates/core/terraform/deploy.sh
  templates/core/terraform/destroy.sh
Labels: safe to test

#1318 Stop inactive CI environments
  .github/workflows/clean_validation_envs.yml
  .github/workflows/deploy_tre_reusable.yml
  devops/scripts/clean_ci_validation_envs.sh
Labels: safe to test

#1328 Fix cleanup script/workflows with no locks
  devops/scripts/clean_ci_validation_envs.sh
  devops/scripts/control_tre.sh
Labels: safe to test

#1345 Fix extended tests results publishing
  .gitignore
  Makefile
Labels: safe to test

#1348 add print
  e2e_tests/helpers.py
Labels: safe to test

#1347 Fix CI ACR Cache Parameter
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_reusable.yml
  devops/scripts/clean_ci_validation_envs.sh
  devops/scripts/control_tre.sh
Labels: safe to test

#1334 Add firewall dependency for gitea/nexus
  templates/core/terraform/main.tf
Labels: safe to test

#1341 Reminder to update docs when making changes
  .github/pull_request_template.md
Labels: safe to test

#1350 Fix broken doc link
  docs/tre-admins/setup-instructions/installing-workspace-service-and-user-resource.md
Labels: safe to test

#1354 Upgrade azurerm to 2.97
  devops/terraform/.terraform.lock.hcl
  devops/terraform/terraform.tf
  templates/core/terraform/.terraform.lock.hcl
  templates/core/terraform/main.tf
  templates/core/terraform/servicebus.tf
  templates/shared_services/gitea/terraform/.terraform.lock.hcl
  templates/shared_services/gitea/terraform/gitea-webapp.tf
  templates/shared_services/gitea/terraform/terraform.tf
  templates/shared_services/sonatype-nexus/terraform/.terraform.lock.hcl
  templates/shared_services/sonatype-nexus/terraform/terraform.tf
  templates/workspace_services/azureml/terraform/.terraform.lock.hcl
  templates/workspace_services/azureml/terraform/main.tf
  templates/workspace_services/azureml/user_resources/aml_compute/terraform/.terraform.lock.hcl
  templates/workspace_services/azureml/user_resources/aml_compute/terraform/main.tf
  templates/workspace_services/devtestlabs/terraform/.terraform.lock.hcl
  templates/workspace_services/devtestlabs/terraform/main.tf
  templates/workspace_services/guacamole/terraform/.terraform.lock.hcl
  templates/workspace_services/guacamole/terraform/main.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/.terraform.lock.hcl
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/main.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/.terraform.lock.hcl
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/main.tf
  templates/workspace_services/innereye/terraform/.terraform.lock.hcl
  templates/workspace_services/innereye/terraform/main.tf
  templates/workspaces/base/terraform/.terraform.lock.hcl
  templates/workspaces/base/terraform/main.tf
Labels: safe to test

#1351 Skip deploy when only md files are updated
  .github/workflows/build_validation_develop.yml
  .github/workflows/deploy_tre.yml
Labels: safe to test

#1357 Fix debug reference in docs
  .github/workflows/build_docs.yml
  docs/tre-admins/environment-variables.md
Labels: safe to test

#1358 A job to free disk space in Resource Processor
  templates/core/terraform/resource_processor/vmss_porter/cloud-config.yaml
Labels: safe to test

#1360 CI checks core image version update
  .github/workflows/build_docker_images.yml
Labels: safe to test

#1364 Set Exit Codes When Returning Errors
  devops/scripts/check_dependencies.sh
Labels: safe to test

#1356 Add pr_comment_bot workflow
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_reusable.yml
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1371 Fix output reference
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1369 Add Alternative Method of running letsencrypt.sh
  templates/core/terraform/scripts/letsencrypt.sh
Labels: safe to test

#1373 Add temp debug step to pr_comment_bot for troubleshooting
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1375 Move user check inside workflow step
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1377 Add output to diagnose permissions + start force-approve command
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1372 Purge keyvaults to allow reuse of the same TRE ID
  .github/workflows/clean_validation_envs.yml
  devops/scripts/clean_ci_validation_envs.sh
  devops/scripts/destroy_env_no_terraform.sh
Labels: safe to test

#1365 Split out Firewall / Nexus / Gitea
  .gitignore
  Makefile
  templates/core/terraform/firewall/output.tf
  templates/core/terraform/firewall/variables.tf
  templates/core/terraform/main.tf
  templates/core/terraform/network/output.tf
  templates/shared_services/deploy_from_local.sh
  templates/shared_services/firewall/.dockerignore
  templates/shared_services/firewall/.gitignore
  templates/shared_services/firewall/Dockerfile.tmpl
  templates/shared_services/firewall/azure.json
  templates/shared_services/firewall/parameters.json
  templates/shared_services/firewall/porter.yaml
  templates/shared_services/firewall/terraform/data.tf
  templates/shared_services/firewall/terraform/firewall.tf
  templates/shared_services/firewall/terraform/import_state.sh
  templates/shared_services/firewall/terraform/locals.tf
  templates/shared_services/firewall/terraform/main.tf
  templates/shared_services/firewall/terraform/remove_state.sh
  templates/shared_services/firewall/terraform/routetable.tf
  templates/shared_services/firewall/terraform/variables.tf
  templates/shared_services/gitea/.dockerignore
  templates/shared_services/gitea/.gitignore
  templates/shared_services/gitea/Dockerfile.tmpl
  templates/shared_services/gitea/azure.json
  templates/shared_services/gitea/parameters.json
  templates/shared_services/gitea/porter.yaml
  templates/shared_services/gitea/terraform/firewall.tf
  templates/shared_services/gitea/terraform/gitea-webapp.tf
  templates/shared_services/gitea/terraform/locals.tf
  templates/shared_services/gitea/terraform/main.tf
  templates/shared_services/gitea/terraform/mysql.tf
  templates/shared_services/gitea/version.txt
  templates/shared_services/sonatype-nexus/.dockerignore
  templates/shared_services/sonatype-nexus/.gitignore
  templates/shared_services/sonatype-nexus/Dockerfile.tmpl
  templates/shared_services/sonatype-nexus/azure.json
  templates/shared_services/sonatype-nexus/parameters.json
  templates/shared_services/sonatype-nexus/porter.yaml
  templates/shared_services/sonatype-nexus/terraform/deploy.sh
  templates/shared_services/sonatype-nexus/terraform/destroy.sh
  templates/shared_services/sonatype-nexus/terraform/locals.tf
  templates/shared_services/sonatype-nexus/terraform/main.tf
  templates/shared_services/sonatype-nexus/terraform/variables.tf
  templates/shared_services/sonatype-nexus/terraform/webapp.tf
Labels: safe to test, breaking-change

#1384 Add link to workflow run
  .github/workflows/pr_comment_bot.yml
Labels: safe to test

#1374 Disable persisting credentials in checkout action
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/build_docker_images.yml
  .github/workflows/build_docs.yml
  .github/workflows/clean_validation_envs.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_tre_reusable.yml
  .github/workflows/e2e.yml
  .github/workflows/lets_encrypt.yml
Labels: safe to test

#1353 Adding ID token (hybrid flow) to the app registration script
  scripts/aad-app-reg.sh
Labels: safe to test

#1387 Fix firewall check in control script
  devops/scripts/control_tre.sh
  devops/scripts/destroy_env_no_terraform.sh
Labels: safe to test

#1388 Diagnostic settings support only sync deletion
  devops/scripts/destroy_env_no_terraform.sh
Labels: safe to test

#1391 tre-start called before deploy-core
  .github/workflows/deploy_tre_reusable.yml
  Makefile
Labels: safe to test
