Repository microsoft/AzureTRE, pull requests merged in 2022-06, with the labels that each got.

#1867 Listing workspace operations. for #1852
  ui/app/src/components/workspaces/ResourceOperationListItem.tsx
  ui/app/src/components/workspaces/ResourceOperationsList.tsx
  ui/app/src/components/workspaces/WorkspaceItem.tsx
Labels: ui

#1957 Fix Guacamole firewall rule name
  templates/workspace_services/guacamole/terraform/firewall.tf
Labels: external

#1956 UI Enhancements
  ui/app/public/favicon.ico
  ui/app/public/index.html
  ui/app/src/App.scss
  ui/app/src/App.tsx
  ui/app/src/components/root/LeftNav.tsx
  ui/app/src/components/root/RootDashboard.tsx
  ui/app/src/components/root/RootLayout.tsx
  ui/app/src/components/shared/ConfirmDeleteResource.tsx
  ui/app/src/components/shared/ConfirmDisableEnableResource.tsx
  ui/app/src/components/shared/CreateUpdateResource/CreateUpdateResource.tsx
  ui/app/src/components/shared/CreateUpdateResource/ResourceForm.tsx
  ui/app/src/components/shared/CreateUpdateResource/SelectTemplate.tsx
  ui/app/src/components/shared/ResourceCard.tsx
  ui/app/src/components/shared/ResourceContextMenu.tsx
  ui/app/src/components/shared/ResourceHeader.tsx
  ui/app/src/components/shared/ResourceHistory.tsx
  ui/app/src/components/shared/ResourceOperationListItem.tsx
  ui/app/src/components/shared/ResourceOperationsList.tsx
  ui/app/src/components/shared/ResourcePropertyPanel.tsx
  ui/app/src/components/shared/SecuredByRole.tsx
  ui/app/src/components/shared/SharedServiceItem.tsx
  ui/app/src/components/shared/SharedServices.tsx
  ui/app/src/components/shared/notifications/NotificationPanel.tsx
  ui/app/src/components/shared/notifications/NotificationPoller.tsx
  ui/app/src/components/workspaces/ResourceOperationsList.tsx
  ui/app/src/components/workspaces/UserResourceItem.tsx
  ui/app/src/components/workspaces/WorkspaceItem.tsx
  ui/app/src/components/workspaces/WorkspaceLeftNav.tsx
  ui/app/src/components/workspaces/WorkspaceProvider.tsx
  ui/app/src/components/workspaces/WorkspaceServiceItem.tsx
  ui/app/src/components/workspaces/WorkspaceServices.tsx
  ui/app/src/contexts/CreateUpdateResourceContext.ts
  ui/app/src/hooks/useAuthApiCall.ts
  ui/app/src/hooks/useComponentManager.ts
  ui/app/src/models/resourceType.ts
Labels: ui

#1972 UI: Resource Status + lifecycles
  api_app/_version.py
  api_app/models/domain/operation.py
  api_app/models/domain/resource.py
  api_app/service_bus/deployment_status_update.py
  ui/app/src/App.scss
  ui/app/src/components/shared/CreateUpdateResource/CreateUpdateResource.tsx
  ui/app/src/components/shared/CreateUpdateResource/ResourceForm.tsx
  ui/app/src/components/shared/ResourceCard.tsx
  ui/app/src/components/shared/ResourceContextMenu.tsx
  ui/app/src/components/shared/ResourceHeader.tsx
  ui/app/src/components/shared/ResourceHistory.tsx
  ui/app/src/components/shared/SharedServiceItem.tsx
  ui/app/src/components/shared/StatusBadge.tsx
  ui/app/src/components/workspaces/UserResourceItem.tsx
  ui/app/src/components/workspaces/WorkspaceItem.tsx
  ui/app/src/components/workspaces/WorkspaceLeftNav.tsx
  ui/app/src/components/workspaces/WorkspaceProvider.tsx
  ui/app/src/components/workspaces/WorkspaceServiceItem.tsx
  ui/app/src/components/workspaces/WorkspaceServices.tsx
  ui/app/src/hooks/useComponentManager.ts
  ui/app/src/models/operation.ts
  ui/app/src/models/resource.ts
Labels: ui

#2000 UI Doc
  docs/tre-developers/ui.md
  mkdocs.yml
  templates/core/terraform/main.tf
  templates/core/terraform/outputs.tf
  ui/app/staticwebapp.config.json
Labels: ui

#2017 Block WS Airlock storage acccounts from public network
  templates/workspaces/base/terraform/airlock/eventgrid_topics.tf
  templates/workspaces/base/terraform/airlock/storage_accounts.tf
  templates/workspaces/base/terraform/workspace.tf
Labels: airlock

#1949 Airlock API (Draft + Submit)
  api_app/.env.sample
  api_app/_version.py
  api_app/api/dependencies/airlock.py
  api_app/api/routes/airlock.py
  api_app/api/routes/airlock_resource_helpers.py
  api_app/api/routes/api.py
  api_app/core/config.py
  api_app/db/repositories/airlock_requests.py
  api_app/db/repositories/airlock_resources.py
  api_app/event_grid/__init__.py
  api_app/event_grid/helpers.py
  api_app/models/domain/airlock_request.py
  api_app/models/domain/airlock_resource.py
  api_app/models/schemas/airlock_request.py
  api_app/requirements.txt
  api_app/resources/strings.py
  templates/core/terraform/airlock/eventgrid_topics.tf
  templates/core/terraform/airlock/output.tf
  templates/core/terraform/airlock/variables.tf
  templates/core/terraform/api-webapp.tf
  templates/core/terraform/json-to-env.sh
  templates/core/terraform/main.tf
  templates/core/terraform/outputs.tf
Labels: airlock

#2005 [cost] Tag Gitea workspace service in Terraform
  templates/workspace_services/gitea/terraform/gitea-webapp.tf
  templates/workspace_services/gitea/terraform/locals.tf
  templates/workspace_services/gitea/terraform/mysql.tf
  templates/workspace_services/gitea/terraform/storage.tf
Labels: external

#1978 Airlock processor handles request Submission
  .devcontainer/devcontainer.json
  airlock_processor/.funcignore
  airlock_processor/BlobCreatedTrigger/__init__.py
  airlock_processor/BlobCreatedTrigger/function.json
  airlock_processor/StatusChangedQueueTrigger/__init__.py
  airlock_processor/StatusChangedQueueTrigger/function.json
  airlock_processor/_version.py
  airlock_processor/exceptions/AirlockInvalidContainerException.py
  airlock_processor/local.settings.json-sample
  airlock_processor/requirements.txt
  airlock_processor/shared_code/blob_operations.py
  airlock_processor/shared_code/constants.py
  airlock_processor/tests/__init__.py
  airlock_processor/tests/test_copy_data.py
  templates/core/terraform/airlock/airlock_processor.tf
  templates/core/terraform/airlock/eventgrid_topics.tf
  templates/core/terraform/airlock/identity.tf
  templates/core/terraform/airlock/locals.tf
  templates/core/terraform/airlock/service_bus.tf
  templates/core/terraform/airlock/variables.tf
  templates/core/terraform/main.tf
  templates/workspaces/base/terraform/airlock/eventgrid_topics.tf
  templates/workspaces/base/terraform/airlock/locals.tf
  templates/workspaces/base/terraform/airlock/storage_accounts.tf
Labels: airlock

#2044 Airlock - API - approve/reject a request
  api_app/_version.py
  api_app/api/routes/airlock.py
  api_app/api/routes/airlock_resource_helpers.py
  api_app/db/repositories/airlock_requests.py
  api_app/db/repositories/airlock_resources.py
  api_app/db/repositories/airlock_reviews.py
  api_app/event_grid/helpers.py
  api_app/models/domain/airlock_request.py
  api_app/models/domain/airlock_resource.py
  api_app/models/domain/airlock_review.py
  api_app/models/schemas/airlock_review.py
  api_app/resources/strings.py
Labels: airlock

#1970 [cost] Tagging Base workspace
  templates/workspaces/base/terraform/aad/aad.tf
  templates/workspaces/base/terraform/aad/variables.tf
  templates/workspaces/base/terraform/airlock/eventgrid_topics.tf
  templates/workspaces/base/terraform/airlock/storage_accounts.tf
  templates/workspaces/base/terraform/airlock/variables.tf
  templates/workspaces/base/terraform/appserviceplan.tf
  templates/workspaces/base/terraform/keyvault.tf
  templates/workspaces/base/terraform/locals.tf
  templates/workspaces/base/terraform/network/network.tf
  templates/workspaces/base/terraform/network/security.tf
  templates/workspaces/base/terraform/network/variables.tf
  templates/workspaces/base/terraform/network/zone_links.tf
  templates/workspaces/base/terraform/storage.tf
  templates/workspaces/base/terraform/variables.tf
  templates/workspaces/base/terraform/workspace.tf
Labels: external

#1998 [cost] Tag innereye Workspace Service in Terraform
  templates/workspace_services/azureml/terraform/acr.tf
  templates/workspace_services/azureml/terraform/acr/.terraform.lock.hcl
  templates/workspace_services/azureml/terraform/acr/main.tf
  templates/workspace_services/azureml/terraform/acr/variables.tf
  templates/workspace_services/azureml/terraform/locals.tf
  templates/workspace_services/azureml/terraform/main.tf
  templates/workspace_services/azureml/terraform/variables.tf
  templates/workspace_services/devtestlabs/terraform/locals.tf
  templates/workspace_services/devtestlabs/terraform/variables.tf
  templates/workspace_services/innereye/terraform/compute.tf
  templates/workspace_services/innereye/terraform/locals.tf
  templates/workspace_services/innereye/terraform/variables.tf
  templates/workspace_services/innereye/terraform/web_app.tf
  templates/workspace_services/mlflow/terraform/.terraform.lock.hcl
  templates/workspace_services/mlflow/terraform/locals.tf
  templates/workspace_services/mlflow/terraform/postgresql.tf
  templates/workspace_services/mlflow/terraform/variables.tf
Labels: external

#2107 fix broken airlock upgrades
  templates/core/terraform/deploy.sh
Labels: airlock

#2061 Guacamole user resource templates tagging
  templates/workspace_services/azureml/user_resources/aml_compute/terraform/compute.tf
  templates/workspace_services/azureml/user_resources/aml_compute/terraform/locals.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/linuxvm.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/locals.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/locals.tf
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/windowsvm.tf
  templates/workspace_services/guacamole/user_resources/guacamole-dev-vm/terraform/linuxvm.tf
  templates/workspace_services/guacamole/user_resources/guacamole-dev-vm/terraform/locals.tf
Labels: external

#2091 [airlock] Create containers
  airlock_processor/StatusChangedQueueTrigger/__init__.py
  airlock_processor/_version.py
  airlock_processor/requirements.txt
  airlock_processor/shared_code/blob_operations.py
  airlock_processor/shared_code/constants.py
  airlock_processor/tests/shared_code/blob_operations.py
Labels: airlock

#2105 Unit tests for Airlock API
  api_app/_version.py
  api_app/api/dependencies/airlock.py
  api_app/api/routes/airlock_resource_helpers.py
  api_app/db/repositories/airlock_requests.py
  api_app/db/repositories/airlock_resources.py
  api_app/db/repositories/airlock_reviews.py
  api_app/tests_ma/test_api/test_routes/test_airlock.py
  api_app/tests_ma/test_api/test_routes/test_airlock_resource_helpers.py
  api_app/tests_ma/test_db/test_repositories/test_airlock_request_repository.py
  api_app/tests_ma/test_db/test_repositories/test_airlock_review_repository.py
Labels: airlock

#2123 Align airlock tags
  templates/core/terraform/airlock/airlock_processor.tf
  templates/core/terraform/airlock/eventgrid_topics.tf
  templates/core/terraform/airlock/identity.tf
  templates/core/terraform/airlock/locals.tf
  templates/core/terraform/airlock/service_bus.tf
  templates/core/terraform/airlock/storage_accounts.tf
  templates/core/terraform/airlock/variables.tf
  templates/core/terraform/main.tf
Labels: airlock

#2095 UI: Add Power state display to resources
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/porter.yaml
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/porter.yaml
  ui/app/package.json
  ui/app/src/App.scss
  ui/app/src/components/shared/PowerStateBadge.tsx
  ui/app/src/components/shared/ResourceCard.tsx
  ui/app/src/components/shared/ResourceContextMenu.tsx
  ui/app/src/components/shared/ResourceHeader.tsx
  ui/app/src/models/resource.ts
  ui/app/yarn.lock
Labels: ui

#2142 TRE API consumes and handles the StepResult event
  api_app/.env.sample
  api_app/_version.py
  api_app/core/config.py
  api_app/db/repositories/airlock_reviews.py
  api_app/main.py
  api_app/models/domain/airlock_operations.py
  api_app/models/domain/airlock_review.py
  api_app/models/schemas/airlock_review.py
  api_app/resources/strings.py
  api_app/service_bus/airlock_request_status_update.py
  api_app/tests_ma/test_db/test_repositories/test_airlock_review_repository.py
  api_app/tests_ma/test_service_bus/test_airlock_request_status_update.py
  templates/core/terraform/airlock/output.tf
  templates/core/terraform/api-webapp.tf
  templates/core/terraform/json-to-env.sh
  templates/core/terraform/outputs.tf
Labels: airlock

#2165 [temp fix] Delay between system topics creation
  templates/core/terraform/airlock/eventgrid_topics.tf
  templates/workspaces/base/porter.yaml
  templates/workspaces/base/terraform/airlock/eventgrid_topics.tf
Labels: airlock

#2145 Fix Cost API Bugs
  api_app/_version.py
  api_app/api/routes/costs.py
  api_app/resources/strings.py
  api_app/services/cost_service.py
  api_app/tests_ma/test_services/test_cost_service.py
Labels: bug

#2163 Airlock - Adding missing blocked storage
  airlock_processor/_version.py
  airlock_processor/shared_code/constants.py
  templates/core/terraform/airlock/eventgrid_topics.tf
  templates/core/terraform/airlock/locals.tf
  templates/core/terraform/airlock/service_bus.tf
  templates/core/terraform/airlock/storage_accounts.tf
  templates/workspaces/base/terraform/airlock/eventgrid_topics.tf
  templates/workspaces/base/terraform/airlock/locals.tf
  templates/workspaces/base/terraform/airlock/storage_accounts.tf
Labels: airlock

#2170 Missing diagnostics for airlock processor function
  templates/core/terraform/airlock/airlock_processor.tf
  templates/core/terraform/airlock/variables.tf
  templates/core/terraform/main.tf
Labels: airlock
