Repository microsoft/AzureTRE, pull requests merged in 2022-12, with the labels that each got.

#2931 Amend conda configuration in Nexus
  templates/shared_services/sonatype-nexus-vm/porter.yaml
  templates/shared_services/sonatype-nexus-vm/scripts/nexus_repos_config/conda_mirror_proxy_conf.json
  templates/shared_services/sonatype-nexus-vm/scripts/nexus_repos_config/conda_proxy_conf.json
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/porter.yaml
  templates/workspace_services/guacamole/user_resources/guacamole-azure-linuxvm/terraform/vm_config.sh
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/porter.yaml
  templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/vm_config.ps1
Labels: external

#2576 change merge properties sequence for defaults
  CHANGELOG.md
  api_app/_version.py
  api_app/services/schema_service.py
  api_app/tests_ma/test_services/test_schema_service.py
Labels: external

#2963 Nexus VM disk size
  templates/shared_services/sonatype-nexus-vm/terraform/vm.tf
Labels: external

#2981 Add option to disable Swagger
  .github/actions/devcontainer_run_command/action.yml
  .github/workflows/deploy_tre.yml
  .github/workflows/deploy_tre_branch.yml
  .github/workflows/deploy_tre_reusable.yml
  .github/workflows/pr_comment_bot.yml
  CHANGELOG.md
  api_app/_version.py
  api_app/api/routes/api.py
  api_app/core/config.py
  api_app/resources/strings.py
  config.sample.yaml
  config_schema.json
  docs/tre-admins/environment-variables.md
  docs/tre-admins/setup-instructions/cicd-pre-deployment-steps.md
  docs/tre-admins/setup-instructions/workflows.md
  templates/core/terraform/api-webapp.tf
  templates/core/terraform/variables.tf
  templates/core/version.txt
Labels: api

#3015 Amend comment about export-inprogress networking
  templates/workspaces/base/terraform/airlock/storage_accounts.tf
Labels: airlock
