Repository microsoft/AzureTRE, pull requests merged in 2023-01, with the labels that each got.

#3044 Add ExceptionTracebackFilter + Replace logging.error with logging.exception in API routes
  api_app/_version.py
  api_app/api/routes/airlock.py
  api_app/api/routes/airlock_resource_helpers.py
  api_app/api/routes/costs.py
  api_app/api/routes/migrations.py
  api_app/api/routes/resource_helpers.py
  api_app/api/routes/shared_services.py
  api_app/api/routes/workspaces.py
  api_app/services/logging.py
Labels: api

#3060 UI - Display the steps of resource operations
  ui/app/package.json
  ui/app/src/components/shared/ResourceOperationStepsList.tsx
  ui/app/src/components/shared/ResourceOperationsList.tsx
Labels: ui

#3071 Fix odd API behavior to illegal patching
  api_app/_version.py
  api_app/db/repositories/resources.py
  api_app/models/schemas/resource.py
  api_app/tests_ma/test_api/test_routes/test_shared_services.py
Labels: api

#3138 Docs versioning
  .github/workflows/build_docs.yml
  docs/requirements.txt
  mkdocs-overrides/main.html
  mkdocs.yml
Labels: documentation

#1857 Adding Azure databricks workspace service
  CHANGELOG.md
  core/terraform/locals.tf
  core/terraform/network/locals.tf
  core/version.txt
  docs/assets/databricks_workspace_service.png
  docs/tre-templates/workspace-services/databricks.md
  mkdocs.yml
  templates/workspace_services/databricks/.dockerignore
  templates/workspace_services/databricks/.env.sample
  templates/workspace_services/databricks/Dockerfile.tmpl
  templates/workspace_services/databricks/README.md
  templates/workspace_services/databricks/parameters.json
  templates/workspace_services/databricks/porter.yaml
  templates/workspace_services/databricks/template_schema.json
  templates/workspace_services/databricks/terraform/.terraform.lock.hcl
  templates/workspace_services/databricks/terraform/data.tf
  templates/workspace_services/databricks/terraform/databricks-udr.json
  templates/workspace_services/databricks/terraform/deploy.sh
  templates/workspace_services/databricks/terraform/locals.tf
  templates/workspace_services/databricks/terraform/main.tf
  templates/workspace_services/databricks/terraform/network.tf
  templates/workspace_services/databricks/terraform/outputs.tf
  templates/workspace_services/databricks/terraform/providers.tf
  templates/workspace_services/databricks/terraform/variables.tf
  templates/workspaces/base/porter.yaml
  templates/workspaces/base/terraform/network/data.tf
  templates/workspaces/base/terraform/network/outputs.tf
  templates/workspaces/base/terraform/network/zone_links.tf
  templates/workspaces/base/terraform/storage.tf
Labels: external
