Repository microsoft/AzureTRE, pull requests merged in 2024-09, with the labels that each got.

#4075 Open AI Workspace Service
  .github/workflows/deploy_tre_reusable.yml
  CHANGELOG.md
  core/terraform/dns_zones_non_core.tf
  core/terraform/locals.tf
  core/terraform/main.tf
  core/version.txt
  docs/tre-templates/workspace-services/openai.md
  e2e_tests/resources/strings.py
  e2e_tests/test_workspace_services.py
  mkdocs.yml
  templates/workspace_services/openai/.env.sample
  templates/workspace_services/openai/Dockerfile.tmpl
  templates/workspace_services/openai/parameters.json
  templates/workspace_services/openai/porter.yaml
  templates/workspace_services/openai/template_schema.json
  templates/workspace_services/openai/terraform/.terraform.lock.hcl
  templates/workspace_services/openai/terraform/locals.tf
  templates/workspace_services/openai/terraform/main.tf
  templates/workspace_services/openai/terraform/openai.tf
  templates/workspace_services/openai/terraform/outputs.tf
  templates/workspace_services/openai/terraform/variables.tf
  templates/workspaces/base/porter.yaml
  templates/workspaces/base/terraform/network/data.tf
  templates/workspaces/base/terraform/network/network.tf
  templates/workspaces/base/terraform/network/zone_links.tf
Labels: external

#4087 Update unrestricted & airlock review workspace base version
  CHANGELOG.md
  templates/workspaces/airlock-import-review/Dockerfile.tmpl
  templates/workspaces/airlock-import-review/porter.yaml
  templates/workspaces/airlock-import-review/terraform/network_output.terraform
  templates/workspaces/unrestricted/Dockerfile.tmpl
  templates/workspaces/unrestricted/porter.yaml
Labels: external

#4096 Workspace creation blocked due to Azure API depreciation - base workspace only
  CHANGELOG.md
  templates/workspaces/base/porter.yaml
  templates/workspaces/base/terraform/.terraform.lock.hcl
  templates/workspaces/base/terraform/azure-monitor/azure-monitor.tf
  templates/workspaces/base/terraform/providers.tf
Labels: external

#4015 Update to Release Docs
  CHANGELOG.md
  docs/tre-developers/release.md
Labels: documentation

#4101 Prep for Release v0.19.1
  CHANGELOG.md
Labels: release
